### ISSUE TITLE
Doesn't support SDK dependencies

### ISSUE THREAD

**Issue by thosakwe** [Andersmholmgren/pubspec#2]
I intend to send in a PR fixing this and the other issues I will describe.

That being said, the package throws in cases like the following:

```yaml
dependencies:
  flutter:
    sdk: flutter
```
